name: docker-publish
on:
    push:
        branches: [main]

jobs:
    docker:
        runs-on: ubuntu-latest
        
        
        steps:
            - name: Checkoout code
              uses: actions/checkout@v4

            - name: Login Docker hub
              if: github.ref == 'refs/heads/main'
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKER_TOKEN }}
                
            - name: Set Short SHA
              run: echo "Short_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

            - name: Docker build image
              uses: docker/build-push-action@v6
              with:
                context: .
                push: false
                tags: |
                    ${{ secrets.DOCKER_USERNAME }}/github-actions-app:latest
                    ${{ secrets.DOCKER_USERNAME }}/github-actions-app:sha-${{ env.SHORT_SHA }}

            - name: Push Docker Image
              if: github.ref == 'ref/heads/main'
              run: |
                docker push ${{ secrets.DOCKER_USERNAME }}/github-actions-app:latest
                docker push ${{ secrets.DOCKER_USERNAME }}/github-actions-app:sha-${{ env.SHORT_SHA }}


