name: secret-read

on:
    workflow_dispatch:

jobs:
    secret:
        runs-on: ubuntu-latest   
        
        steps:
            - name: read secret
              run: echo "my secret is ${{ secrets.MY_SECRET_MESSAGE }}"