name: Self hosted

on:
    workflow_dispatch:

jobs:
    self_hosted:
        runs-on: self-hosted
        
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Run a test
              run: "Running on self-hosted runner!"