name: Self hosted

on:
    workflow_dispatch:

jobs:
    self_hosted:
        runs-on: [self-hosted, my-linux-runner]

        
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Run a test
              run: echo "Running on self-hosted runner!"