name: smart pipeline

on:
    push:
        branches:
            - main

jobs:

    lint:
        runs-on: ubuntu-latest

        steps:
            - name: lint job
              run: echo "checking lint"

    test:
        runs-on: ubuntu-latest
        steps:
            - name: test step
              run: echo "test checking"

    summary:
        runs-on: ubuntu-latest
        needs: [lint, test]
        steps:
            - name: Print branches name and commit message
              run: |
                echo "commmit message: ${{ github.event.head_commit.message }}"
                
                if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
                 echo "This is a MAIN branch push"
                else
                  echo "This is a FEATURE branch push"
                fi
