name: Use Composite Action

on:
    workflow_dispatch:
  #push:
    #branches:
      #- main

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Custom Action
        id: greet_step
        uses: ./.github/actions/setup-and-greet
        with:
          name: "Shashank"
          language: "hi"

      - name: Print Output
        run: |
          echo "Was greeted: ${{ steps.greet_step.outputs.greeted }}"